name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup GoogleService-Info.plist
      run: |
        mkdir -p MediStock/Configurations
        cat > MediStock/Configurations/GoogleService-Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>API_KEY</key>
            <string>AIzaSyDummyKeyForTestingPurposesOnly123456</string>
            <key>GCM_SENDER_ID</key>
            <string>123456789012</string>
            <key>PLIST_VERSION</key>
            <string>1</string>
            <key>BUNDLE_ID</key>
            <string>com.rebonnte.MediStock</string>
            <key>PROJECT_ID</key>
            <string>medistock-test</string>
            <key>STORAGE_BUCKET</key>
            <string>medistock-test.appspot.com</string>
            <key>IS_ADS_ENABLED</key>
            <false/>
            <key>IS_ANALYTICS_ENABLED</key>
            <false/>
            <key>IS_APPINVITE_ENABLED</key>
            <false/>
            <key>IS_GCM_ENABLED</key>
            <true/>
            <key>IS_SIGNIN_ENABLED</key>
            <true/>
            <key>GOOGLE_APP_ID</key>
            <string>1:123456789012:ios:abcdef1234567890</string>
            <key>DATABASE_URL</key>
            <string>https://medistock-test.firebaseio.com</string>
        </dict>
        </plist>
        EOF
    
    - name: Disable Firebase in tests
      run: |
        # Commente FirebaseApp.configure() pour les tests
        sed -i '' 's/FirebaseApp.configure()/\/\/ FirebaseApp.configure() \/\/ Disabled for CI tests/' MediStock/AppDelegate.swift
    
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project MediStock.xcodeproj \
          -scheme MediStock \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
          -only-testing:MediStockTests \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          /Users/runner/Library/Developer/Xcode/DerivedData/MediStock-*/Logs/Test/*.xcresult
