name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test MediStock
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
      
      - name: List Available Simulators
        run: xcrun simctl list devices available
      
      - name: Get Available Simulator
        id: simulator
        run: |
          # Trouve le premier iPhone disponible et extrait son UUID
          SIMULATOR_INFO=$(xcrun simctl list devices available iPhone | grep "iPhone" | head -1)
          echo "Found simulator: $SIMULATOR_INFO"
          UDID=$(echo "$SIMULATOR_INFO" | grep -o '[A-F0-9]\{8\}-[A-F0-9]\{4\}-[A-F0-9]\{4\}-[A-F0-9]\{4\}-[A-F0-9]\{12\}')
          echo "udid=$UDID" >> $GITHUB_OUTPUT
          echo "Using simulator UDID: $UDID"
      
      - name: Create Mock GoogleService-Info.plist
        run: |
          cat > MediStock/GoogleService-Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>API_KEY</key>
            <string>AIzaSyDummyKeyForCI123456789012345</string>
            <key>GCM_SENDER_ID</key>
            <string>123456789012</string>
            <key>PLIST_VERSION</key>
            <string>1</string>
            <key>BUNDLE_ID</key>
            <string>com.rebonnte.MediStock</string>
            <key>PROJECT_ID</key>
            <string>medistock-ci-test</string>
            <key>STORAGE_BUCKET</key>
            <string>medistock-ci-test.appspot.com</string>
            <key>IS_ADS_ENABLED</key>
            <false/>
            <key>IS_ANALYTICS_ENABLED</key>
            <false/>
            <key>IS_APPINVITE_ENABLED</key>
            <false/>
            <key>IS_GCM_ENABLED</key>
            <true/>
            <key>IS_SIGNIN_ENABLED</key>
            <true/>
            <key>GOOGLE_APP_ID</key>
            <string>1:123456789012:ios:abcdef1234567890abcdef</string>
            <key>DATABASE_URL</key>
            <string>https://medistock-ci-test.firebaseio.com</string>
          </dict>
          </plist>
          EOF
      
      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
          -scheme "MediStock" \
          -project "MediStock.xcodeproj"
      
      - name: Build MediStock
        run: |
          xcodebuild build-for-testing \
          -scheme "MediStock" \
          -project "MediStock.xcodeproj" \
          -destination "platform=iOS Simulator,id=${{ steps.simulator.outputs.udid }}"
      
      - name: Run Unit Tests
        run: |
          xcodebuild test-without-building \
          -scheme "MediStock" \
          -project "MediStock.xcodeproj" \
          -destination "platform=iOS Simulator,id=${{ steps.simulator.outputs.udid }}" \
          -only-testing:MediStockTests
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ~/Library/Logs/DiagnosticReports/
            ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/
