name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Find AppDelegate
      run: find . -name "AppDelegate.swift" -type f
    
    - name: Setup GoogleService-Info.plist
      run: |
        mkdir -p MediStock/Configurations
        cat > MediStock/Configurations/GoogleService-Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>API_KEY</key>
            <string>AIzaSyDummyKeyForTestingPurposesOnly123456</string>
            <key>GCM_SENDER_ID</key>
            <string>123456789012</string>
            <key>GOOGLE_APP_ID</key>
            <string>1:123456789012:ios:abcdef1234567890</string>
            <key>PROJECT_ID</key>
            <string>medistock-test</string>
        </dict>
        </plist>
        EOF
    
    - name: Disable Firebase in tests
      run: |
        APPDELEGATE=$(find . -name "AppDelegate.swift" -type f | head -n 1)
        if [ -f "$APPDELEGATE" ]; then
          sed -i '' 's/FirebaseApp.configure()/\/\/ FirebaseApp.configure()/' "$APPDELEGATE"
        fi
    
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project MediStock.xcodeproj \
          -scheme MediStock \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
          -only-testing:MediStockTests \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          /Users/runner/Library/Developer/Xcode/DerivedData/MediStock-*/Logs/Test/*.xcresult
