name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test MediStock
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Build MediStock
        run: |
          xcodebuild build-for-testing \
          -scheme "MediStock" \
          -project "MediStock.xcodeproj" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest"

      - name: Test MediStock
        run: |
          xcodebuild test-without-building \
          -scheme "MediStock" \
          -project "MediStock.xcodeproj" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=latest"
