name: iOS CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test MediStock
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Install CocoaPods
        run: |
          if [ -f "Podfile" ]; then
            sudo gem install cocoapods
            pod install
          fi

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -workspace "MediStock.xcworkspace" \
            -scheme "MediStock" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

      - name: Test
        run: |
          xcodebuild test-without-building \
            -workspace "MediStock.xcworkspace" \
            -scheme "MediStock" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
