name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_SERVICE_INFO: ${{ secrets.GOOGLE_SERVICE_INFO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Install dependencies
        run: |
          swift package resolve

      - name: Write GoogleService-Info.plist
        run: |
          echo "$GOOGLE_SERVICE_INFO" | base64 --decode > ./MediStock/Configurations/GoogleService-Info.plist

      - name: Build
        run: |
          xcodebuild -scheme MediStock -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' build

      - name: Test
        run: |
          xcodebuild -scheme MediStock -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' test
