name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    env:
      PLIST_SECRET_NAME: GOOGLE_SERVICE_INFO_PLIST
      PROJECT_NAME: MediStock
      SCHEME_NAME: MediStock
      WORKSPACE_NAME: MediStock.xcworkspace
      DESTINATION: "platform=iOS Simulator,name=iPhone 14,OS=17.5"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v3
      with:
        xcode-version: '15.1'

    - name: Install dependencies
      run: |
        brew install cocoapods
        pod install --project-directory=.

    - name: Create GoogleService-Info.plist
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ./MediStock/Configurations/GoogleService-Info.plist

    - name: Build and test
      run: |
        xcodebuild clean test \
          -workspace $WORKSPACE_NAME \
          -scheme $SCHEME_NAME \
          -destination "$DESTINATION" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          DEVELOPMENT_TEAM=""
