name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-14
    env:
      TESTING: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Create GoogleService-Info.plist
        run: |
          mkdir -p MediStock/Configurations
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > MediStock/Configurations/GoogleService-Info.plist

      - name: Build and Test
        run: |
          xcodebuild test \
            -project MediStock.xcodeproj \
            -scheme MediStock \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5' \
            -only-testing:MediStockTests \
            -resultBundlePath TestResults \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults.xcresult
          retention-days: 5
